config/routes.rb
HubSlideshows::Application.routes.draw do
  
  resources :hubs, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  
  match '/play/:hub_id', to: 'static_pages#play', as: 'play'
  match 'playone/:project_id', to: 'static_pages#play_one', as: 'play_one'
  
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  
  match '/project/:id', to: 'projects#destroy', via: :delete, as: 'project'
  match '/project/:id/toggleapproval', to: 'projects#toggle_approval', via: :post, as: 'toggle_project_approval'
  
  match '/new', to: 'frontend#new', via: :get, as: 'new_project'
  match '/new', to: 'frontend#new_project_from_json', via: :post, as: 'new_project_from_json'
  
  match '/manage/:id/:key', to: 'frontend#edit', via: :get, as: 'edit_project'
  match '/manage/:id/:key', to: 'frontend#update_project_from_json', via: :put, as: 'update_project_from_json'
  
  
  match '/createasset', to: 'frontend#create_asset', as: 'create_asset'
  
  root :to => 'static_pages#home'
  

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  
  before_filter :correct_key, only: [:edit, :update_project_from_json]
  
  def new
    @project = Project.new
    render :layout => 'frontend'
  end
  
  def edit
    render :layout => 'frontend'
  end
  
  def new_project_from_json
    @project = Project.new
    save_project_json
    UserMailer.project_created(@project).deliver
  end
  
  def update_project_from_json
    save_project_json
  end
  
  def create_asset
    
    case params[:upload_form][:type]
    when 'photo'
      uploader = PhotoUploader.new
    when 'logo'
      uploader = LogoUploader.new
    when 'misc_image'
      uploader = MiscImageUploader.new
    when 'avatar'
      uploader = AvatarUploader.new
    end
    
    begin
      uploader.store!(params[:upload_form][:uploaded_data])
      render :json => { asset_url: uploader.url }
    rescue CarrierWave::IntegrityError
      render :json => { error: 'Error!' }
    end
  
  end
  
  private
  
    def correct_key
      @project = Project.find(params[:id])
      redirect_to root_path unless @project.key == params[:key]
    end
  
    def save_project_json
      
      project = ActiveSupport::JSON.decode(params["project"])

      @project.hub_id = project["hub_id"].to_i
      @project.name = project["name"]
      @project.email = project["email"]
      @project.logo = project["logo"]
      @project.misc_image = project["misc_image"]
      
      @project.approved = false

      if @project.save
        
        @project.pages.delete_all

        project["slides"].each do |page|

          @page = @project.pages.build
          @page[:page_type] = page["page_type"]

          @page.content = page["content"]

          @page.save

        end

        render :json => { id: @project.id, edit_project_path: edit_project_url(@project.id, @project.key) }

      else
        render :json => { errors: @project.errors.each {|x| x} }
      end
      
    end
  
end

app/views/frontend/_basic_info.html.haml
%h2 Basic info

.row

  .span3
    First, give us some basic info
    about your project or organization.

  .span9
    .form-horizontal

      .control-group
        = label_tag :hub_id, nil, class: 'control-label'
        .controls
          = select_tag :hub_id, options_for_select(all_hubs, @project.hub_id)

      .control-group
        = label_tag :name, nil, class: 'control-label'
        .controls
          = text_field_tag :name, @project.name

      .control-group
        = label_tag :email, nil, class: 'control-label'
        .controls
          = text_field_tag :email, @project.email
    

      = form_for(:upload_form, url: create_asset_path, html: { method: :post, class: 'upload-form', |
        :"data-url-input" => 'misc_image', multipart: true }, remote: true ) do |f| |
        .control-group
          = label_tag :misc_image, "Logo", class: 'control-label'
          .controls.file-controls{class: ('uploaded' if !@project.misc_image.blank?)}
            = f.hidden_field :type, value: 'misc_image'
            = f.file_field :uploaded_data
            = render 'upload_feedback', image_url: @project.misc_image
            = hidden_field_tag :misc_image, @project.misc_image, class: 'file-url'  
            .file-info
              Will be shrunk and used in the corner of each slide.
               
               

app/views/frontend/_slide.html.haml
- page ||= Page.new

.slide{id: ('template-slide' if template_slide)}
  .heading
    .handle
      %i.icon-align-justify
    %a.toggle Big Text
    .delete-slide
      %i.icon-trash#delete-slide
    .toggle-display
      %i.icon-chevron-down
      %i.icon-chevron-up
  .content
    .form-horizontal
      .control-group
        = label_tag :page_type, nil, class: 'control-label'
        .controls
          = select_tag :page_type, options_for_select(all_page_types, page.page_type), class: 'page-type-select'
        
      -############### Big Text ###############
      .page-type.big-text{:"data-page-type" => "Big Text"}
        .control-group
          = label_tag "Text", nil, class: 'control-label'
          .controls
            = text_area_tag :"big_text[text]", (page.content["text"] if page.page_type == "Big Text")
          
    
      -############### Big Photo ###############
      .page-type.big-photo{:"data-page-type" => "Big Photo"}
        = form_for(:upload_form, url: create_asset_path, html: { method: :post, class: 'upload-form', |
          :"data-url-input" => 'big_photo_url', multipart: true }, remote: true ) do |f| |
          .control-group
            = label_tag :"big_photo[url]", 'Photo', class: 'control-label'
            .controls.file-controls{class: ('uploaded' if page.page_type == "Big Photo" && !page.content["url"].blank?)}
              = f.hidden_field :type, value: 'photo'
              = f.file_field :uploaded_data
              = render 'upload_feedback', image_url: (page.content["url"] if page.page_type == "Big Photo")
              = hidden_field_tag :"big_photo[url]", (page.content["url"] if page.page_type == "Big Photo"), |
                  class: 'file-url' |
        
      -############### Logo ###############
      .page-type.big-photo{:"data-page-type" => "Logo"}
        = form_for(:upload_form, url: create_asset_path, html: { method: :post, class: 'upload-form', |
          :"data-url-input" => 'logo_url', multipart: true }, remote: true ) do |f| |
          .control-group
            = label_tag :"logo[url]", 'Photo', class: 'control-label'
            .controls.file-controls{class: ('uploaded' if page.page_type == "Logo" && !page.content["url"].blank?)}
              = f.hidden_field :type, value: 'photo'
              = f.file_field :uploaded_data
              = render 'upload_feedback', image_url: (page.content["url"] if page.page_type == "Logo")
              = hidden_field_tag :"logo[url]", (page.content["url"] if page.page_type == "Logo"), |
                  class: 'file-url' |

    
      -############### Text and Photo ###############
      .page-type.text-and-photo{:"data-page-type" => "Text and Photo"}
        .control-group
          = label_tag "Text", nil, class: 'control-label'
          .controls
            = text_area_tag :"text_and_photo[text]", (page.content["text"] if page.page_type == "Text and Photo")
            
        = form_for(:upload_form, url: create_asset_path, html: { method: :post, class: 'upload-form', |
          :"data-url-input" => 'text_and_photo_url', multipart: true }, remote: true ) do |f| |
          .control-group
            = label_tag :"text_and_photo[url]", 'Photo', class: 'control-label'
            .controls.file-controls{class: ('uploaded' if page.page_type == "Text and Photo" && !page.content["url"].blank?)}
              = f.hidden_field :type, value: 'photo'
              = f.file_field :uploaded_data
              = render 'upload_feedback', image_url: (page.content["url"] if page.page_type == "Text and Photo")
              = hidden_field_tag :"text_and_photo[url]", (page.content["url"] if page.page_type == "Text and Photo"), |
                  class: 'file-url' |
            
          
          
      -############### Team Bios ###############
      .page-type.team-bios{:"data-page-type" => "Team Bios"}
        - (1..2).each do |n|
          %h5 Team member ##{n}
    
          .control-group
            = label_tag "Name", nil, class: 'control-label'
            .controls
              = text_field_tag :"team_bios[member_#{n}_name]", (page.content["member_#{n}_name"] if page.page_type == "Team Bios")
            
          .control-group
            = label_tag "Title", nil, class: 'control-label'
            .controls
              = text_field_tag :"team_bios[member_#{n}_title]", (page.content["member_#{n}_title"] if page.page_type == "Team Bios")
              
          = form_for(:upload_form, url: create_asset_path, html: { method: :post, class: 'upload-form', |
            :"data-url-input" => "team_bios_member_#{n}_photo", multipart: true }, remote: true ) do |f| |
            .control-group
              = label_tag :"team_bios[member_#{n}_photo]", 'Photo', class: 'control-label'
              .controls.file-controls{class: ('uploaded' if page.page_type == "Team Bios" && !page.content["member_#{n}_photo"].blank?)}
                = f.hidden_field :type, value: 'avatar'
                = f.file_field :uploaded_data
                = render 'upload_feedback', image_url: (page.content["member_#{n}_photo"] if page.page_type == "Team Bios")
                = hidden_field_tag :"team_bios[member_#{n}_photo]", |
                  (page.content["member_#{n}_photo"] if page.page_type == "Team Bios"), |    
                  class: 'file-url' |
                .file-info
                  We'll crop this to 200x200px.
          
            
            
      -############### Contact Info ###############
      .page-type.contact-info{:"data-page-type" => "Contact Info"}
        .control-group
          = label_tag "Mailing Address", nil, class: 'control-label'
          .controls
            = text_area_tag :"contact_info[mailing_address]", |
                (page.content["mailing_address"] if page.page_type == "Contact Info"), |
                placeholder: "Include company name" |
    
        .control-group
          = label_tag "Phone", nil, class: 'control-label'
          .controls
            = text_field_tag :"contact_info[phone]", (page.content["phone"] if page.page_type == "Contact Info")
          
        .control-group
          = label_tag "Website", nil, class: 'control-label'
          .controls
            .input-prepend
              %span.add-on http://
              = text_field_tag :"contact_info[website]", (page.content["website"] if page.page_type == "Contact Info")
          
        .control-group
          = label_tag "Twitter", nil, class: 'control-label'
          .controls
            .input-prepend
              %span.add-on @
              = text_field_tag :"contact_info[twitter]", (page.content["twitter"] if page.page_type == "Contact Info")
          
        .control-group
          = label_tag "Facebook", nil, class: 'control-label'
          .controls
            .input-prepend
              %span.add-on facebook.com/
              = text_field_tag :"contact_info[facebook]", (page.content["facebook"] if page.page_type == "Contact Info")
          
        .control-group
          = label_tag "Blog", nil, class: 'control-label'
          .controls
            .input-prepend
              %span.add-on http://
              = text_field_tag :"contact_info[blog]", (page.content["blog"] if page.page_type == "Contact Info")

app/views/frontend/_upload_feedback.html.haml
%span.image-anchor
  %a{target: "_blank", href: image_url}
    %img{src: image_url}

%span.spinner= image_tag 'spinner.gif'
%span.remove
  %a (remove)

app/views/frontend/edit.html.haml
- provide(:title, "Edit Project #{@project.name}")
- provide(:body_class, "project")

%h1= "Edit Project: #{@project.name}"
%a.btn.btn-primary.btn-large{href: play_one_path(@project.id), target: '_blank'} Preview Project
%hr

#project-page

  = render 'basic_info'
  
  %hr

  %h2 Slides

  .row

    .span3
      Now, configure the slides of
      your presentation. You can drag
      them to change the order.

    .span9
      %a.pull-right.btn.new-slide-btn Add New Slide

      .slides#sortable
        = render 'slide', template_slide: true
      
        - @project.pages.each do |page|
          = render 'slide', template_slide: false, page: page
          
  .form-actions
    %button.btn.btn-primary.btn-large#submit-btn{"data-loading-text" => "Saving...", |
      "data-submit-url" => update_project_from_json_path(@project.id, @project.key), "data-method" => "PUT" } Save
    %span.saved Saved changes!

app/views/frontend/new.html.haml
- provide(:title, "New Project")
- provide(:body_class, "project")

%h1 Add Project to Slideshow
%hr

#project-page

  = render 'basic_info'
  
  %hr  

  %h2 Slides

  .row

    .span3
      Now, configure the slides of
      your presentation. You can drag
      them to change the order.

    .span9
      %a.pull-right.btn.new-slide-btn Add New Slide

      .slides#sortable
        = render 'slide', template_slide: true          
          
  .form-actions
    %button.btn.btn-primary.btn-large#submit-btn{"data-loading-text" => "Saving...", |
      "data-submit-url" => new_project_from_json_path, "data-method" => "POST" } Save and Preview

#success-page
  .alert.alert-success
    %strong Project saved!
    Keep this link to edit it in the future:
    %a#edit-project-path