config/routes.rb
HubSlideshows::Application.routes.draw do
  
  resources :hubs, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  
  match '/play/:hub_id', to: 'static_pages#play', as: 'play'
  match 'playone/:project_id', to: 'static_pages#play_one', as: 'play_one'
  
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  
  match '/project/:id', to: 'projects#destroy', via: :delete, as: 'project'
  match '/project/:id/toggleapproval', to: 'projects#toggle_approval', via: :post, as: 'toggle_project_approval'
  
  match '/new', to: 'frontend#new', via: :get, as: 'new_project'
  match '/new', to: 'frontend#new_project_from_json', via: :post, as: 'new_project_from_json'
  
  match '/manage/:id/:key', to: 'frontend#edit', via: :get, as: 'edit_project'
  match '/manage/:id/:key', to: 'frontend#update_project_from_json', via: :put, as: 'update_project_from_json'
  
  
  match '/createasset', to: 'frontend#create_asset', as: 'create_asset'
  
  root :to => 'static_pages#home'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @projects = current_hub.projects.all
    else
      redirect_to signin_path
    end
  end
  
  def play
    @hub = Hub.find(params[:hub_id])
    @projects = @hub.projects.where(approved: true)
    @slide_params = {x: 0, y: 0, page_count: 1, project_count: 1}
    render :layout => false
  end
  
  def play_one
    @projects = Project.where(id: params[:project_id])
    @hub = Hub.find(@projects[0].hub)
    @slide_params = {x: 0, y: 0, page_count: 1, project_count: 1}
    render "play", layout: false
  end
end

app/views/static_pages/home.html.haml
%h1 
  Projects for #{current_hub.name}
  %span.pull-right
    %a.btn.btn-primary{ href: new_project_path } Add Project
    %a.btn.btn-success{ href: play_path(current_hub) } Play Slideshow

%table.table.table-bordered.table-striped
  %tr
    %th Project Name
    %th Email
    %th Approved?
    %th Actions
  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.email
      %td
        = project.approved ? 'Yes' : 'No'
        - if project.approved
          = link_to '(Unapprove)', toggle_project_approval_path(project.id), method: :post
        - else
          = link_to '(Approve)', toggle_project_approval_path(project.id), method: :post
      %td
        = link_to 'delete', project, method: :delete, confirm: "Are you sure you want to delete this project?"
        &middot;
        = link_to 'edit', edit_project_path(project.id, project.key)

app/views/static_pages/play.html.haml
!!! 5

%html{lang: "en"}
%head
  %title Hub Slideshow
  = stylesheet_link_tag "slideshow", media: "all"
  %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,700,600", rel: "stylesheet", type: "text/css"}
  
%body.impress-not-supported

  %img#hub-logo{src: "https://s3.amazonaws.com/HubSlideshows/uploads/project/ce4f5ffb-5959-452c-b826-e349c624ac25.png"}
  
  #impress
  
    //big overview step-# data-scale * 30 = data-x
    
    .step{"id" => "members", "data-x" => "1100", "data-y" => -4000, "data-rotate-x" => "45", "data-scale" => 4}
      Our #{@hub.name} Members    
    
    - @projects.each do |project|
    
      - before_project
    
      //title step
      .step.title-step{"data-x" => @slide_params[:x] + 1000, |
                       "data-y" => @slide_params[:y] + 400,  |
                       "data-scale" => "2.5", "id" => "project#{project.id}"} |
        .project-title= project.name
          
      - project.pages.all.each do |page|
          
        .step{"data-x" => @slide_params[:x], "data-y" => @slide_params[:y]}
          = render "steps/" + partial_name_from(page.page_type), page: page, project: project
          - after_page
          
      //overview step
      .step{"data-x" => @slide_params[:orig_x] + 1000, "data-y" => @slide_params[:orig_y] + 400, "data-scale" => "2.5"}
      
      - after_project  

  .hint
    %p Use a spacebar or arrow keys to navigate
    

  = javascript_include_tag "slideshow"
    
    