config/routes.rb
HubSlideshows::Application.routes.draw do
  
  resources :hubs, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  
  match '/play/:hub_id', to: 'static_pages#play', as: 'play'
  match 'playone/:project_id', to: 'static_pages#play_one', as: 'play_one'
  
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  
  match '/project/:id', to: 'projects#destroy', via: :delete, as: 'project'
  match '/project/:id/toggleapproval', to: 'projects#toggle_approval', via: :post, as: 'toggle_project_approval'
  
  match '/new', to: 'frontend#new', via: :get, as: 'new_project'
  match '/new', to: 'frontend#new_project_from_json', via: :post, as: 'new_project_from_json'
  
  match '/manage/:id/:key', to: 'frontend#edit', via: :get, as: 'edit_project'
  match '/manage/:id/:key', to: 'frontend#update_project_from_json', via: :put, as: 'update_project_from_json'
  
  
  match '/createasset', to: 'frontend#create_asset', as: 'create_asset'
  
  root :to => 'static_pages#home'
  

end

app/models/hub.rb
# == Schema Information
#
# Table name: hubs
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  remember_token  :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

class Hub < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  has_many :projects, dependent: :destroy
  
  before_save { |hub| hub.email = email.downcase }
  before_save :create_remember_token
    
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  default_scope order: 'hubs.name'
  
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController

  def new
    @hub = Hub.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hub }
    end
  end

  # POST /hubs
  # POST /hubs.json
  def create
    @hub = Hub.new(params[:hub])

    respond_to do |format|
      if @hub.save
        format.html { redirect_to root_path, notice: 'Hub was successfully created.' }
        format.json { render json: @hub, status: :created, location: @hub }
      else
        format.html { render action: "new" }
        format.json { render json: @hub.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/views/hubs/_form.html.erb
<%= form_for(@hub) do |f| %>
  <% if @hub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hub.errors.count, "error") %> prohibited this hub from being saved:</h2>

      <ul>
      <% @hub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hubs/edit.html.erb
<h1>Editing hub</h1>

<%= render 'form' %>

<%= link_to 'Show', @hub %> |
<%= link_to 'Back', hubs_path %>

app/views/hubs/index.html.erb
<h1>Listing hubs</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hubs.each do |hub| %>
  <tr>
    <td><%= hub.name %></td>
    <td><%= link_to 'Show', hub %></td>
    <td><%= link_to 'Edit', edit_hub_path(hub) %></td>
    <td><%= link_to 'Destroy', hub, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hub', new_hub_path %>

app/views/hubs/new.html.erb
<h1>New hub</h1>

<%= render 'form' %>

<%= link_to 'Back', hubs_path %>

app/views/hubs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hub_path(@hub) %> |
<%= link_to 'Back', hubs_path %>