config/routes.rb
HubSlideshows::Application.routes.draw do
  
  resources :hubs, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  
  match '/play/:hub_id', to: 'static_pages#play', as: 'play'
  match 'playone/:project_id', to: 'static_pages#play_one', as: 'play_one'
  
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  
  match '/project/:id', to: 'projects#destroy', via: :delete, as: 'project'
  match '/project/:id/toggleapproval', to: 'projects#toggle_approval', via: :post, as: 'toggle_project_approval'
  
  match '/new', to: 'frontend#new', via: :get, as: 'new_project'
  match '/new', to: 'frontend#new_project_from_json', via: :post, as: 'new_project_from_json'
  
  match '/manage/:id/:key', to: 'frontend#edit', via: :get, as: 'edit_project'
  match '/manage/:id/:key', to: 'frontend#update_project_from_json', via: :put, as: 'update_project_from_json'
  
  
  match '/createasset', to: 'frontend#create_asset', as: 'create_asset'
  
  root :to => 'static_pages#home'
  

end

app/views/layouts/_frontend_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.brand{href: '/'} Hub Slideshows

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.brand{href: '/'} Hub Slideshows
      .nav-collapse
        %ul.nav.pull-right
          %li 
            - if signed_in?
              %li.dropdown
                %a.dropdown-toggle{ href: "#", :"data-toggle" => "dropdown" }
                  = current_hub.name
                  %b.caret  
                %ul.dropdown-menu
                  %li
                    = link_to 'Play Slideshow', play_path(current_hub)
                  %li
                    = link_to 'Sign out', signout_path, method: :delete
            - else
              = link_to 'Sign in', signin_path

app/views/layouts/_shim.html.haml
:erb

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!! 5

%head
  %title= full_title(yield(:title))
  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  = render 'layouts/shim'
  
%body
  = render 'layouts/header'
  .container
    - flash.each do |key, value|
      = content_tag(:div, value, class: "alert alert-#{key}")
  
    = yield

app/views/layouts/frontend.html.haml
!!! 5

%head
  %title= full_title(yield(:title))
  = stylesheet_link_tag "frontend", media: "all"
  = javascript_include_tag "frontend"
  = csrf_meta_tags
  = render 'layouts/shim'
  
%body{class: yield(:body_class)}
  = render 'layouts/frontend_header'
  .container
    - flash.each do |key, value|
      = content_tag(:div, value, class: "alert alert-#{key}")
  
    = yield